apiVersion: 1

deleteDatasources:
  - name: MySQL
    orgId: 1

datasources:
- name: MySQL
  type: mysql
  access: proxy
  orgId: 1
  url: db:3306
  password: ""
  user: ${MYSQL_USER}
  database: ${MYSQL_DATABASE}
  basicAuth: false
  isDefault: true
  secureJsonData:
    password: ${MYSQL_PASSWORD}
  editable: false 
