{
 "title": "Call Statistics",
 "time": { "from": "now-14d", "to": "now+1d" },
 "templating": {
  "list": [
   { "name": "groups", "label": "Groups", "query": "SELECT alias FROM groups;" },
   { "name": "time_unit", "label": "Time unit", "query": "1m, 1h, 1d, 7d, 1M, 6M, 1y" }
  ]
 },
 "panels": [
  {
   "title": "active calls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM calls c\nWHERE c.answered_at IS NOT NULL AND \n      c.end IS NULL;\n"
    }
   ]
  },
  {
   "title": "waiting in queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM calls c\nWHERE c.answered_at IS NULL AND\n      c.hangup_cause IS NULL\n"
    }
   ]
  },
  {
   "title": "outgoing pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  0 as time,\n  count(DISTINCT call_id) as \"answered\"\nFROM calls as c, groups as g\nWHERE $__timeFilter(start) AND direction=\"out\" AND answered_at IS NOT NULL AND (\"${groups}\"=\"\" OR c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')"
    },
    {
     "rawSql": "SELECT\n  0 as time,\n  count(DISTINCT call_id) as \"unanswered\"\nFROM calls as c, groups as g\nWHERE $__timeFilter(start) AND direction=\"out\" AND answered_at IS NULL AND (\"${groups}\"=\"\" OR c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')"
    }
   ]
  },
  {
   "title": "incoming pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  0 as time,\n  count(DISTINCT call_id) as \"answered\"\nFROM calls as c, groups as g\nWHERE $__timeFilter(start) AND direction=\"in\" AND answered_at IS NOT NULL AND (\"${groups}\"=\"'None'\" OR c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')"
    },
    {
     "rawSql": "SELECT\n  0 as time,\n  count(DISTINCT call_id) as \"unanswered\"\nFROM calls as c, groups as g\nWHERE $__timeFilter(start) AND direction=\"in\" AND answered_at IS NULL AND (\"${groups}\"=\"'None'\" OR c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')"
    }
   ]
  },
  {
   "title": "total calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\ncount(*) as \"total\"\nFROM calls as c, groups as g\nWHERE \"${groups}\"=\"'None'\" OR (c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\n  count(DISTINCT call_id) as \"incoming\"\nFROM calls as c, groups as g\nWHERE direction='in' AND (\"${groups}\"=\"'None'\" OR (c.group_extension=g.extension AND alias REGEXP '${groups:pipe}'))\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\n  count(DISTINCT call_id) as \"outgoing\"\nFROM calls as c, groups as g\nWHERE direction='out' AND (\"${groups}\"=\"'None'\" OR (c.group_extension=g.extension AND alias REGEXP '${groups:pipe}'))\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "outgoing calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "calls" } },
   "yaxes": [
    { "format": "calls" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\n  count(DISTINCT call_id) as \"answered\"\nFROM calls as c, groups as g\nWHERE direction='out' AND answered_at IS NOT NULL AND (\"${groups}\"=\"'None'\" OR c.group_extension=g.extension AND  alias REGEXP '${groups:pipe}')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\n  count(DISTINCT call_id) as \"declined\"\nFROM calls as c, groups as g\nWHERE direction='out' AND answered_at IS NULL AND (\"${groups}\"=\"'None'\" OR c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "mean call answer time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\n  AVG(TIME_TO_SEC(TIMEDIFF(answered_at, start))) as \"time in seconds\"\nFROM calls as c, groups as g\nWHERE $__timeFilter(start) AND (\"${groups}\"=\"'None'\" OR answered_at IS NOT NULL AND c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "incoming calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "calls" } },
   "yaxes": [
    { "format": "calls" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\n  count(DISTINCT call_id) as \"answered\"\nFROM calls as c, groups as g\nWHERE direction='in' AND answered_at IS NOT NULL AND (\"${groups}\"=\"'None'\" OR c.group_extension=g.extension AND  alias REGEXP '${groups:pipe}')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\n  count(DISTINCT call_id) as \"declined\"\nFROM calls as c, groups g\nWHERE direction='in' AND answered_at IS NULL AND (\"${groups}\"=\"'None'\" OR c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "average call duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(answered_at, '$time_unit', 0) as time_sec,\n  AVG(TIME_TO_SEC(TIMEDIFF(end, answered_at))) as \"time in seconds\"\nFROM calls as c, groups as g\nWHERE $__timeFilter(start) AND answered_at IS NOT NULL AND (\"${groups}\"=\"'None'\" OR c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')\nAND not voicemail\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total voicemail calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start, '$time_unit', 0) as time_sec,\ncount(*) as \"total\"\nFROM calls as c, groups as g\nWHERE \"${groups}\"=\"'None'\" OR (c.group_extension=g.extension AND alias REGEXP '${groups:pipe}')\nAND voicemail\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Longest waiting numbers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  caller_number as Number,\n  TIMEDIFF(answered_at, start) as Duration\nFROM calls\nWHERE $__timeFilter(start)\nAND answered_at IS NOT NULL\nAND direction = \"in\"\nORDER BY Duration DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Most calling numbers ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  caller_number as Number,\n  count(*) as Count\nFROM calls\nWHERE $__timeFilter(start)\nAND direction = \"in\"\ngroup by caller_number\nORDER BY count desc\nLIMIT 5"
    }
   ]
  }
 ]
}